#!/usr/bin/env bash

# Displays all of the colors available to the current terminal.

i=0
colors=$(tput colors)
len=${#colors}
end="$(tput sgr0)"

while [ $i -lt $colors ]; do
    start="$(tput setaf $i)"
    printf "${start}%${len}d${end} " $i

    ((i++))

    if ((i % 16 == 0)); then
        echo
    fi
done
