#!/usr/bin/env bash

# $1: A number of milliseconds.
#
# Displays a number of milliseconds in a human readable format.

total_milliseconds=$1
total_seconds=$((total_milliseconds / 1000))
total_minutes=$((total_seconds / 60))
total_hours=$((total_minutes / 60))
total_days=$((total_hours / 24))

milliseconds=$((total_milliseconds % 1000))
seconds=$((total_seconds % 60))
minutes=$((total_minutes % 60))
hours=$((total_hours % 24))

parts=()
add_part() {
  [[ $2 -ne 1 ]] && local ending="s"
  parts+=( "$(printf "${1}%s" "${@:2}" $ending)" )
}
maybe_add_part() {
  if [[ $2 -gt 0 ]]; then
    add_part "$@"
  fi
}

maybe_add_part '%d day' "${total_days}"
maybe_add_part '%d hour' "${hours}"
maybe_add_part '%d minute' "${minutes}"

desc="seconds"
if [[ "${seconds}" -eq 1 && "${milliseconds}" -eq 0 ]]; then
  desc="second"
fi
parts+=( "$(printf "%d.%03d %s" "${seconds}" "${milliseconds}" "${desc}")" )

num_parts=${#parts[@]}
if [[ ${num_parts} -gt 1 ]]; then
    parts[num_parts]=${parts[num_parts - 1]}
    parts[num_parts - 1]="and"
fi

echo "${parts[*]}"
