#!/usr/bin/env bash
# Searches for a docker container with name=$1, and executes $2+ in interactive
# mode.
# e.g. docker-exec-it plex /bin/bash

mapfile -t ids < <(docker ps --filter "name=$1" --format "{{.ID}}")
if [[ ${#ids[@]} -eq 0 ]]; then
    echo "No container matching name=$1 was found." 1>&2
    exit 1
fi

names=()
for id in "${ids[@]}"; do
    names+=( "$(docker container inspect "${id}" --format "{{.Name}}")" )
done

if [[ ${#ids[@]} -eq 1 ]]; then
    id="${ids[0]}"
    echo "Running in ${names[0]}..."
else
    select _ in "${names[@]}"; do
        id="${ids[${REPLY}-1]}"
        break
    done
fi

docker exec -it "${id}" "${@:2}"
