#!/usr/bin/env bash

# $1: A number of seconds
# $2+: A command to run with arguments
#
# Run notify-send if the command takes longer than $1 seconds

if [[ -z $DISPLAY ]]; then
    exec "${@:2}"
fi

max=$1
command="${*:2}"
begin=$(date +%s)
alerted=0

_alert() {
    local exit_status=$?

    if ((!alerted)); then
        alerted=1
        local end=$(date +%s)

        local elapsed=$((end - begin))
        if [[ $elapsed -ge $max ]]; then
            icon=$([[ $exit_status == 0 ]] && echo info || echo error)
            summary="Command took $(display-seconds $elapsed) to complete."

            notify-send --urgency=low -i "$icon" "$summary" "$command"
        fi
    fi

    exit $exit_status
}
trap '_alert' INT QUIT TERM EXIT

( "${@:2}" )
