#!/usr/bin/env bash

for f in "$@"; do
    contents="$(tail -n +3 "$f")"
    lines=()
    while [[ "${contents}" =~ ([^$'\r']+)$'\r' ]]; do
        line="${BASH_REMATCH[1]}"
        contents="${contents:${#BASH_REMATCH[0]}}"

        IFS=$'\n'
        split=( ${line} )
        unset IFS

        line="${split[*]}"

        lines+=( "${line}" )
    done

    printf "%s\n" "${lines[@]::${#lines[@]}-1}" > "$f"
done
