#!/usr/bin/env bash

# $@: mkv files.
#
# Performs several actions in sequence:
#   1) Looks for a file that doesn't end with .mkv in $1's directory
#       1.1) If a non-mkv file is found, renames $1 to that file with .mkv added
#       1.2) Remove the non-mkv file
#   2) Calls update-permissions
#   3) Calls tag-mkv

for file in "$@"; do
    dir=$(dirname "$file")
    file_name=$(basename "$file")

    next_episode=$(find "$dir" -maxdepth 1 -type f -name 'E[0-9][0-9]*' -not -name '*.mkv' | sort | head -1)
    next_episode_name=$(basename "$next_episode")

    if [[ -n $next_episode_name ]]; then
        new_file="${next_episode}.mkv"
        new_file_name="${next_episode_name}.mkv"
        echo "Renaming $file_name to $new_file_name"

        if [[ -f $new_file ]]; then
            echo "$new_file_name already exists."
            exit 1
        fi

        mv "$file" "$new_file"
        if [[ $? != 0 ]]; then
            exit 1
        fi

        file=$new_file
        file_name=$new_file_name

        echo "Removing placeholder for $file_name"
        rm "$next_episode"
    fi

    echo "Updating permissions of $file_name"
    update-permissions "$file"

    echo "Tagging $file_name"
    tag-mkv "$file"
done
