#!/usr/bin/env bash
# Sends a command to all tmux panes in the current server.

for pane in $(tmux list-panes -aF "#D"); do
  tmux send-keys -t "${pane}" "$*"
  tmux send-keys -t "${pane}" "Enter"
done
