#!/usr/bin/env bash
UNIFI_SSH_FLAGS="${UNIFI_SSH_FLAGS:--i ~/.ssh/unifi_backup -l backup-generator}"
UNIFI_CONNECTION="${UNIFI_CONNECTION:-unifi}"

set -u

[[ $# -eq 1 ]] || exit 1
backup_dir="$1"

rsync -e "ssh ${UNIFI_SSH_FLAGS}" --archive ${UNIFI_CONNECTION}:/data/autobackup/ "${backup_dir}"
if [[ $? != 0 ]]; then
    exit 1
fi
