#!/usr/bin/env bash
newline=$'\n'
SLUG_REGEX="(^|${newline})slug: \"?([^ \"${newline}]+)\"?(${newline}|$)"
OWNING_USER="backup-generator"
DEST="$(eval echo ~${OWNING_USER})"

set -u

[[ $# -eq 0 ]] || exit 1

slug="$(ha backups new)"
if [[ $? != 0 ]]; then
    echo "Failed to create hass backup." 1>&2
    exit 1
fi

if [[ ! "${slug}" =~ ${SLUG_REGEX} ]]; then
    echo "Unrecognized backup output: ${slug}" 1>&2
    exit 1
fi
slug="${BASH_REMATCH[2]}"

mv "/backup/${slug}.tar" "${DEST}/${slug}.tar"
if [[ $? != 0 ]]; then
    echo "Could not move backup ${slug} to ${DEST}"
    exit 1
fi

chown "${OWNING_USER}:${OWNING_USER}" "${DEST}/${slug}.tar"
if [[ $? != 0 ]]; then
    echo "Failed to update permissions on backup ${slug}" 1>&2
    exit 1
fi

echo "${DEST}/${slug}.tar"
